### ISSUE TITLE
Feature add - When to claim referrals

### ISSUE THREAD

**Issue by Xgamer911** [Xgamer911/cotps_script#6]
Add config option to let user decide when to claim referrals. At the beginning of each cycle or before trades happen.

I am going to defer to francis on this one. I am relevantly new to this cotps and francis might know things I dont.

**Comment by ghost** [comment]
I'd do once x seconds or so, maybe every hour? But before making a transaction, so you get to instantly trade with your new profits.

**Comment by Xgamer911** [comment]
added in [commit](https://github.com/Xgamer911/cotps_script/commit/d869f2a986de4ff123438eab7c556dcf18d1e7c2)
