### ISSUE TITLE
Todo fix - When sell button isnt found

### ISSUE THREAD

**Issue by Xgamer911** [Xgamer911/cotps_script#7]
When sell button isn't found, the script breaks out and goes into waiting the cycle. I am going to change this to immediately go back into trading if the wallet is more than $5.

**Comment by ghost** [comment]
Sounds fair. All you need is a page reload basically

**Comment by Xgamer911** [comment]
Added in [commit](https://github.com/Xgamer911/cotps_script/commit/6806c4f88f717dc441741eb1e86c672ca2c4d4e6)
