### ISSUE TITLE
Permit two instances running side by side on same machine

### ISSUE THREAD

**Issue by solverware** [Xgamer911/cotps_script#8]
Is it possible to run two side by side installations each with their own config file in separate directories? Will each instance of the python program know which browser instance or browser tab it is interacting with? Thanks!

**Comment by Xgamer911** [comment]
I just tested this for you and you can run two instances on the same machine. Simply get two copies of the script in two different folders and it should run just fine.

**Comment by solverware** [comment]
Cool! Thanks! I know the script will run in two folders but was unsure how each might handle a single Chrome instance with two different accounts, if it will run as two different tabs, or two browser instances each with its own auth credentials.

**Comment by Xgamer911** [comment]
It will open two separate chrome windows.

**Comment by solverware** [comment]
beautiful!
